/* exported error_explanations */

var error_explanations = {
  "description": "URLs that explain some common JSHint error codes",
  "author": "Nate Silva",
  "notes": "Currently manually maintained :-(",

  "E009": "http://jslinterrors.com/option-validthis-cant-be-used-in-a-global-scope/",
  "E010": "http://jslinterrors.com/with-is-not-allowed-in-strict-mode/",
  "E011": "http://jslinterrors.com/const-a-has-already-been-declared/",
  "E013": "http://jslinterrors.com/attempting-to-override-a-which-is-a-constant/",
  "E014": "http://jslinterrors.com/a-regular-expression-literal-can-be-confused-with/",
  "E015": "http://jslinterrors.com/unclosed-regular-expression/",
  "E017": "http://jslinterrors.com/unclosed-comment/",
  "E029": "http://jslinterrors.com/unclosed-string/",
  "E039": "http://jslinterrors.com/function-declarations-are-not-invocable/",
  "E042": "http://jslinterrors.com/stopping/",
  "I003": "http://jslinterrors.com/es5-option-is-now-set-per-default/",
  "W008": "http://jslinterrors.com/a-leading-decimal-point-can-be-confused-with-a-dot-a/",
  "W009": "http://jslinterrors.com/the-array-literal-notation-is-preferrable/",
  "W010": "http://jslinterrors.com/the-object-literal-notation-is-preferrable/",
  "W019": "http://jslinterrors.com/use-the-isnan-function-to-compare-with-nan/",
  "W020": "http://jslinterrors.com/read-only/",
  "W022": "http://jslinterrors.com/do-not-assign-to-the-exception-parameter/",
  "W024": "http://jslinterrors.com/expected-an-identifier-and-instead-saw-a-a-reserved-word/",
  "W025": "http://jslinterrors.com/missing-name-in-function-declaration/",
  "W031": "http://jslinterrors.com/do-not-use-new-for-side-effects/",
  "W032": "http://jslinterrors.com/unnecessary-semicolon/",
  "W037": "http://jslinterrors.com/a-is-a-statement-label/",
  "W051": "http://jslinterrors.com/variables-should-not-be-deleted/",
  "W052": "http://jslinterrors.com/unexpected-a/",
  "W053": "http://jslinterrors.com/do-not-use-a-as-a-constructor/",
  "W054": "http://jslinterrors.com/the-function-constructor-is-a-form-of-eval/",
  "W055": "http://jslinterrors.com/a-constructor-name-should-start-with-an-uppercase-letter/",
  "W058": "http://jslinterrors.com/missing-invoking-a-constructor/",
  "W061": "http://jslinterrors.com/eval-can-be-harmful/",
  "W062": "http://jslinterrors.com/wrap-an-immediate-function-invocation-in-parentheses/",
  "W063": "http://jslinterrors.com/a-is-not-a-function/",
  "W065": "http://jslinterrors.com/missing-radix-parameter/",
  "W066": "http://jslinterrors.com/implied-eval-consider-passing-a-function/",
  "W068": "http://jslinterrors.com/wrapping-non-iife-function-literals-in-parens/",
  "W069": "http://jslinterrors.com/a-is-better-written-in-dot-notation/",
  "W070": "http://jslinterrors.com/extra-comma/",
  "W072": "http://jslinterrors.com/this-function-has-too-many-parameters/",
  "W075": "http://jslinterrors.com/duplicate-key-a/",
  "W076": "http://jslinterrors.com/unexpected-parameter-a-in-get-b-function/",
  "W079": "http://jslinterrors.com/redefinition-of-a/",
  "W080": "http://jslinterrors.com/it-is-not-necessary-to-initialize-a-to-undefined/",
  "W082": "http://jslinterrors.com/function-declarations-should-not-be-placed-in-blocks/",
  "W083": "http://jslinterrors.com/dont-make-functions-within-a-loop/",
  "W084": "http://jslinterrors.com/expected-a-conditional-expression-and-saw-an-assignment/",
  "W085": "http://jslinterrors.com/dont-use-with/",
  "W087": "http://jslinterrors.com/forgotten-debugger-statement/",
  "W089": "http://jslinterrors.com/the-body-of-a-for-in-should-be-wrapped-in-an-if-statement/",
  "W090": "http://jslinterrors.com/a-is-not-a-statement-label/",
  "W093": "http://jslinterrors.com/did-you-mean-to-return-a-conditional/",
  "W098": "http://jslinterrors.com/a-is-defined-but-never-used/",
  "W105": "http://jslinterrors.com/unexpected-dangling-_-in-a/",
  "W108": "http://jslinterrors.com/strings-must-use-singlequote/",
  "W109": "http://jslinterrors.com/strings-must-use-singlequote/",
  "W110": "http://jslinterrors.com/mixed-double-and-single-quotes/",
  "W115": "http://jslinterrors.com/octal-literals-are-not-allowed-in-strict-mode/",
  "W117": "http://jslinterrors.com/a-is-not-defined/",
  "W120": "http://jslinterrors.com/you-might-be-leaking-a-variable-here/"
};
